-- 009_qr_payments.sql
-- Run this in the Supabase SQL editor. Safe to re-run any number of times.
--
-- Adds the "Pay by QR" flow: a dealer taps "Pay by QR", we ask Cashfree for
-- a dynamic UPI QR tied to one order (amount + expiry), the dealer scans it
-- with WHICHEVER UPI app they have (PhonePe / GPay / Paytm / BHIM — Cashfree
-- doesn't care), and the moment Cashfree confirms the payment it hits our
-- webhook (api/payments/webhook.js), which inserts the row into `payments`
-- itself. No staff verification step for these — the gateway IS the
-- verification, the same way a bank confirming a transfer is.
--
-- This is a parallel path to 005_payment_verification.sql's dealer
-- self-report flow, not a replacement for it: a dealer can still type in
-- "I paid by UPI, here's the UTR" for something they paid outside the app
-- (e.g. straight from their bank app to your VPA) — that still needs staff
-- verification, because we have no independent proof. A QR generated BY
-- this app and confirmed BY the gateway needs no such step.

-- One row per QR shown to a dealer. `status` moves pending -> paid (webhook
-- fires) or pending -> expired (nothing arrived before qr_expires_at — see
-- api/payments/create-qr.js for how that's checked on read, since Postgres
-- has no built-in "expire this row automatically" trigger).
create table if not exists payment_qr_requests (
  id uuid primary key default gen_random_uuid(),
  dealer_id uuid not null references dealers(id),
  application_id uuid references applications(id),
  amount numeric not null check (amount > 0),
  cf_order_id text not null unique,        -- the order_id we sent Cashfree (also its idempotency key)
  qr_expires_at timestamptz not null,      -- mirrors the order_expiry_time we told Cashfree
  status text not null default 'pending' check (status in ('pending', 'paid', 'expired', 'failed')),
  payment_id uuid references payments(id), -- set once the webhook has inserted the payments row
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists payment_qr_requests_dealer_idx on payment_qr_requests(dealer_id);
create index if not exists payment_qr_requests_status_idx on payment_qr_requests(status);

alter table payment_qr_requests enable row level security;

drop policy if exists "staff full access qr requests" on payment_qr_requests;
create policy "staff full access qr requests" on payment_qr_requests
  for all
  using (exists (select 1 from staff where staff.auth_user_id = auth.uid()))
  with check (exists (select 1 from staff where staff.auth_user_id = auth.uid()));

-- Dealers (and their active sub-staff) can only ever READ their own QR
-- requests, to watch pending -> paid happen. They never insert or update
-- one directly from the browser — that would mean the anon key alone could
-- mark a payment "paid", which defeats the entire point. Every write to
-- this table happens server-side (api/payments/create-qr.js and
-- api/payments/webhook.js) using the Supabase service role key, which
-- bypasses RLS entirely.
drop policy if exists "dealer read own qr requests" on payment_qr_requests;
create policy "dealer read own qr requests" on payment_qr_requests
  for select
  using (
    exists (select 1 from dealers where dealers.id = payment_qr_requests.dealer_id and dealers.auth_user_id = auth.uid())
    or exists (select 1 from dealer_staff ds where ds.dealer_id = payment_qr_requests.dealer_id and ds.auth_user_id = auth.uid() and ds.active)
  );

-- payments.submitted_by (added in 005_payment_verification.sql) only
-- allowed 'staff' / 'dealer'. Add 'gateway' for rows the webhook inserts
-- itself, so Receipts / reports can tell "dealer typed this in, unverified
-- until staff checks it" apart from "Cashfree confirmed this, done".
alter table payments drop constraint if exists payments_submitted_by_check;
alter table payments
  add constraint payments_submitted_by_check
  check (submitted_by in ('staff', 'dealer', 'gateway'));

-- Verify:
select conname, pg_get_constraintdef(oid)
from pg_constraint
where conrelid = 'payments'::regclass and conname = 'payments_submitted_by_check';

-- Lets QrPaymentPanel.jsx subscribe to row updates on this table (so the
-- dealer's screen flips to "Paid" the instant the webhook writes it,
-- instead of waiting for the 5s fallback poll). Safe to re-run -- adding a
-- table that's already in the publication is a no-op error we swallow here.
do $$
begin
  alter publication supabase_realtime add table payment_qr_requests;
exception
  when duplicate_object then null;
end $$;
