// src/lib/delhiPoliceStations.js
//
// Fixed list of Delhi Police station names, used to populate the "Police
// Station" dropdown on PCC-required applications (New Application forms +
// Applicant Details editor) instead of free-text entry — keeps names
// consistent so they match cleanly on the printed PCC request letter.
export const DELHI_POLICE_STATIONS = [
  "ADARSH NAGAR", "ALIPUR", "AMAN VIHAR", "AMAR COLONY", "AMB. NAGAR",
  "ANAND PARBAT", "ANAND VIHAR", "ASHOK VIHAR", "B.H.RAO", "BABA HARI DASS NAGAR",
  "BADAR PUR", "BARAKHAMBA ROAD", "BAWANA", "BEGUM PUR", "BHAJAN PURA",
  "BHALSWA DAIRY", "BHARAT NAGAR", "BINDA PUR", "BUDH VIHAR", "BURARI",
  "C. R. PARK", "CHANAKYA PURI", "CHANDANI MAHAL", "CHHAWALA", "CIVIL LINES",
  "CON. PLACE", "D.B.G. ROAD", "DABRI", "DARYA GANJ", "DAYAL PUR",
  "DEFENCE COLONY", "DELHI CANTT", "DWARKA NORTH", "DWARKA SECTOR 23", "DWARKA SOUTH",
  "FARSH BAZAR", "FATEHPUR BERI", "GANDHI NAGAR", "GEETA COLONY", "GHAZIPUR",
  "GOKUL PURI", "GOVIND PURI", "GREATER KAILASH", "GTB ENCLAVE", "GULABI BAGH",
  "H. N. DIN", "HARI NAGAR", "HARSH VIHAR", "HAUZ KHAS", "HAUZ QAZI",
  "I.P. ESTATE", "IITF PRAGATI MAIDAN", "INDER PURI", "JAFFERPUR KALAN", "JAGAT PURI",
  "JAHANGIR PURI", "JAIT PUR", "JAMA MASJID", "JAMIA NAGAR", "JANAK PURI",
  "JYOTI NAGAR", "K.GATE", "K.M.PUR", "K.N.KATJU MARG", "KALANDI KUNJ",
  "KALKAJI", "KALYAN PURI", "KAMLA MKT.", "KANJHAWLA", "KAPSHERA",
  "KARAWAL NAGAR", "KAROL BAGH", "Kartavya Path", "KESHAV PURAM", "KHAJURI KHAS",
  "KHYALA", "KIRSHNA NAGAR", "KIRTI NAGAR", "KISHAN GARH", "KOTWALI",
  "LAHORI GATE", "LAJPAT NAGAR", "LAXMI NAGAR", "LODHI COLONY", "MADHU VIHAR",
  "MAHENDRA PARK", "MAIDAN GARHI", "MALVIYA NAGAR", "MANDAWALI", "MANDIR MARG",
  "MANGOL PURI", "MANSAROVER PARK", "MAURYA ENCLAVE", "MAYA PURI", "MAYUR VIHAR",
  "MEHRAULI", "MODEL TOWN", "MOHAN GARDEN", "MOTI NAGAR", "MOURICE NAGAR",
  "MUKHERJI NAGAR", "MUNDKA", "N. F. COLONY", "NABI KARIM", "NAJAFGARH",
  "NAND NAGARI", "NANGLOI", "NARAINA", "NARELA", "NARELA INDUSTRIAL AREA",
  "NEB SARAI", "NEW ASHOK NAGAR", "NEW USMAN PUR", "NIHAL VIHAR", "NORTH AEVENUE",
  "NORTH ROHINI", "OKHLA IND. AREA", "PAHAR GANJ", "PALAM VILLAGE", "PANDAV NAGAR",
  "PARLIAMENT STREET", "PARSAD NAGAR", "PASCHIM VIHAR EAST", "PASCHIM VIHAR WEST", "PATEL NAGAR",
  "PATPARGANJ INDUSTRIAL AREA", "PRASHANT VIHAR", "PREET VIHAR", "PREM VIHAR", "PUL PRAHLAD PUR",
  "PUNJABI BAGH", "R. K. PURAM", "RAJ PARK", "RAJINDER NAGAR", "RAJOURI GARDEN",
  "RANHOLA", "RANI BAGH", "RANJIT NAGAR", "ROOP NAGAR", "SADAR BAZAR",
  "SAFDARJUNG ENCLAVE", "SAGAR PUR", "SAKET", "SAMAI PUR BADLI", "SANGAM VIHAR",
  "SARAI ROHILLA", "SARITA VIHAR", "SAROJINI NAGAR", "SEELAM PUR", "SEEMA PURI",
  "SHAHADRA", "SHAHBAD DAIRY", "SHAHEEN BAGH", "SHAKAR PUR", "SHALIMAR BAGH",
  "SHASTRI PARK", "SONIA VIHAR", "SOUTH AEVENUE", "SOUTH CAMPUS", "SOUTH ROHINI",
  "SUBHASH PLACE", "SUBZI MANDI", "SULTAN PURI", "SUNLIGHT COLONY", "SWARUP NAGAR",
  "TIGRI", "TILAK MARG", "TILAK NAGAR", "TIMAR PUR", "TUGLAK ROAD",
  "UTTAM NAGAR", "VASANT KUNJ NORTH", "VASANT KUNJ SOUTH", "VASANT VIHAR", "VIJAY VIHAR",
  "VIKAS PURI", "VIVEK VIHAR", "WAZIRABAD", "WELCOME", "ZAFRABAD",
];
